[package]
name = "midatopay_starknet"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
build = "scarb build"
